server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices-user
spring.datasource.username=postgres
spring.datasource.password=****
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.addresses=amqps://*****:1b5_JQDzRHQGEKshgJ33HudVyRnDAg7p@chameleon.lmq.cloudamqp.com/eajgsddj
broker.queue.email.name=default.email
